name: C++ Code Integration

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential cmake git
                git clone https://github.com/google/googletest.git -b v1.15.2
                cd googletest
                mkdir build
                cd build
                cmake ..
                sudo make install

            - name: Build and Test
              run: |
                mkdir build
                cd build
                cmake ..
                make
                ./test_calculator
